### PR TITLE
Move functions to /utils

### PR DESCRIPTION
**Pull request by hafizmuhammadshoaib**

### CODE REVIEW

**Comment by shaansubbaiah** [comment]
You haven't modified the paths, results in an error while building.

```
█▀█ █▀█ █▀█ ▀█▀ █▀▀ █▀█ █░░ █ █▀█
█▀▀ █▄█ █▀▄ ░█░ █▀░ █▄█ █▄▄ █ █▄█
https://github.com/shaansubbaiah/Portfolio

1. Set Github Token 
2. Set configuration options 
3. Build Portfolio 
4. Exit 
Choice: 3

Starting Build
[Error: ENOENT: no such file or directory, open '/home/shaan/Github/Portfolio/utils/config.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/shaan/Github/Portfolio/utils/config.json'
}
[Error: ENOENT: no such file or directory, open '/home/shaan/Github/Portfolio/utils/config.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/shaan/Github/Portfolio/utils/config.json'
}
⚠️ Failed!
Error: Cannot read property 'username' of undefined
```

**Comment by shaansubbaiah** [comment]
I think even the `config.json` will be created in /utils instead of the root directory, which has to be fixed.

**Comment by hafizmuhammadshoaib** [comment]
Okay doing it

**Comment by hafizmuhammadshoaib** [comment]
pushed commit

**Comment by hafizmuhammadshoaib** [comment]
@shaansubbaiah please review the PR.

**Comment by shaansubbaiah** [comment]
Tested, `config.json` still gets created in the utils/ directory

**Comment by hafizmuhammadshoaib** [comment]
okay will do it.

**Comment by shaansubbaiah** [comment]
Can you also remove the formatting changes L40-41, L130-131, L272-273. I'm currently using `Prettier` to format JS, I'll add it to the repo after this PR.

**Comment by hafizmuhammadshoaib** [comment]
i have solved the conflicts

**Comment by hafizmuhammadshoaib** [comment]
i am also using prettier

**Comment by shaansubbaiah** [comment]
Tested, works well! Thanks. Merging.

**Pull request merged**
