### PR TITLE
Add Frosted Glass Effect

### PR DESCRIPTION
**Pull request by sebanti10**
Added the frosted glass effect in the resources/index.css after testing the same in /dist folder.

### CODE REVIEW

**Comment by shaansubbaiah** [comment]
How do I test this properly? I tried setting a background to the html and the card background is not blurry.

image

**Comment by sebanti10** [comment]
I applied the following under resources/index.css in "root" for color-mode="light" _(line 7)_ to check if it works for background image:

```
:root[color-mode="light"] {
    background-image: url(https://i.stack.imgur.com/fhEwl.png);
    background-size: cover;
    background-attachment: fixed;
   /* rest of the code */
}
```

I was able to achieve the following result:
portfolio_screenshot

Please let me know if this was not the actual requirement or if you were looking for something different.. I am really new to open source and I would love to understand your requirements better :)

**Comment by shaansubbaiah** [comment]
Thanks. Looks great!
Turns out that CSS property `backdrop-filter` is only supported on Chrome-based browsers at the moment. When tested on Firefox, it is translucent without a blur. Can you replicate the same effect using the regular CSS `filter` property?

**Comment by sebanti10** [comment]
Thank you :) I am going to try for regular CSS and send a PR.

**Comment by finki70** [comment]
Are you still working on this? @sebanti10

**Comment by shaansubbaiah** [comment]
Closing due to inactivity

**Pull request closed without merging**
