### PR TITLE
Serve github avatar from own assets

### LINKED ISSUE #24: Download avatar
As I said in #23 , I would like to serve everything locally, so we could download the avatar in `build.js` (variable `dt.user.avatarUrl`) and store it into `/dist/assets/png/avatar.png`. Then we dont need build.js line 86-96 anymore.

Also a nice first issue, but I can also work on it by myself.

### PR DESCRIPTION
**Pull request by tomhooijenga**
This should fix #24

### CODE REVIEW

**Comment by shaansubbaiah** [comment]
@tomhooijenga Thanks! Yet to test but there seem to be no issues.

Could you also allow the user to choose a custom picture instead of their GitHub profile picture? I had mentioned in [my comment earlier](https://github.com/shaansubbaiah/Portfolio/issues/24#issuecomment-702954540).

Similar to the other config options, we'd have to ask the user if they want to load a custom picture and if they decide not to, use the GitHub profile picture. The custom picture location would be stored in `config.json`

**Comment by tomhooijenga** [comment]
I can have a look at that. Do we want to support both local and hosted/remote images?

**Comment by shaansubbaiah** [comment]
Not sure, but for now I think just local is fine. Just make sure the user is aware that only local image paths can be supplied. 
However, if you want to make it support both, you can do that instead.

**Comment by shaansubbaiah** [comment]
Tested, works well. Love that it now shows previous config values. Merging :smile:

**Pull request merged**
